typography_spectrum: 0.25849
color:
  brandColors:
    - '#7494bd'
    - '#070707'
    - '#444746'
    - '#747876'
    - '#cbd7d1'
  brandStrength: 0.4117569464724511
  lightness: 0.9757865280844271
  saturation: 0.6213448257185519
  rhythmicContrast: 0.9793461551889777
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49904
analytics:
  google: null
  facebook: null
  twitter: null
name: Hope4Asia
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Give to Love Asia Fund
    url: loveasia.info
    type: external
favicon: null
title: H O P E  4  A S I A
purpose: []
